apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: reference-orders-raw-to-curated
  namespace: spark
  labels:
    app.kubernetes.io/name: reference-orders-raw-to-curated
    reference.dc-platform/component: spark-raw-to-curated
spec:
  type: Python
  mode: cluster
  sparkVersion: "3.5.3"
  image: "${REFERENCE_SPARK_IMAGE}"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/dc-platform/jobs/02_transform_raw_to_curated.py
  deps:
    packages:
      - org.apache.hadoop:hadoop-aws:3.3.4
  arguments:
    - --raw-path
    - s3a://dc-platform-bss-proto-lakehouse-7901580-us-east-1/reference/raw/orders/
    - --curated-path
    - s3a://dc-platform-bss-proto-lakehouse-7901580-us-east-1/reference/curated/orders/
  sparkConf:
    "spark.app.name": "reference-orders-raw-to-curated"
    "spark.ui.prometheus.enabled": "true"
    "spark.executor.processTreeMetrics.enabled": "true"
    "spark.metrics.conf.*.sink.prometheusServlet.class": "org.apache.spark.metrics.sink.PrometheusServlet"
    "spark.metrics.conf.driver.sink.prometheusServlet.path": "/metrics/driver/prometheus/"
    "spark.metrics.conf.executor.sink.prometheusServlet.path": "/metrics/executors/prometheus/"
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "s3a://dc-platform-bss-proto-lakehouse-7901580-us-east-1/reference/spark-event-logs"
    "spark.eventLog.rolling.enabled": "true"
    "spark.eventLog.rolling.maxFileSize": "64m"
    "spark.eventLog.compress": "true"
    "spark.kubernetes.driver.annotation.prometheus.io/scrape": "true"
    "spark.kubernetes.driver.annotation.prometheus.io/path": "/metrics/driver/prometheus/"
    "spark.kubernetes.driver.annotation.prometheus.io/port": "4040"
    "spark.kubernetes.driver.service.annotation.prometheus.io/scrape": "true"
    "spark.kubernetes.driver.service.annotation.prometheus.io/path": "/metrics/driver/prometheus/"
    "spark.kubernetes.driver.service.annotation.prometheus.io/port": "4040"
    "spark.hadoop.fs.s3a.aws.credentials.provider.mapping": "com.amazonaws.auth.WebIdentityTokenCredentialsProvider=software.amazon.awssdk.auth.credentials.ContainerCredentialsProvider"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "software.amazon.awssdk.auth.credentials.ContainerCredentialsProvider"
    "spark.hadoop.fs.s3.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.path.style.access": "false"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "1g"
    serviceAccount: spark-sa
    nodeSelector:
      NodeGroupType: workload
  executor:
    instances: 1
    cores: 1
    coreLimit: "1000m"
    memory: "1g"
    serviceAccount: spark-sa
    nodeSelector:
      NodeGroupType: workload
