apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: orders-dlq
  namespace: kafka
  labels:
    strimzi.io/cluster: reference-kafka
spec:
  topicName: orders_dlq
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: delete
    min.insync.replicas: 1
    retention.ms: 604800000
    segment.bytes: 1073741824
