apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  namespace: kafka
  labels:
    strimzi.io/cluster: reference-kafka
spec:
  replicas: 1
  roles:
    - broker
  resources:
    requests:
      cpu: 400m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
        class: gp2
  template:
    pod:
      metadata:
        labels:
          workload-role: kafka-broker
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: NodeGroupType
                    operator: In
                    values:
                      - workload
