apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-client
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka-test-client
spec:
  restartPolicy: Never
  nodeSelector:
    NodeGroupType: workload
  containers:
    - name: kafka-cli
      image: quay.io/strimzi/kafka:0.51.0-kafka-4.1.0
      command:
        - /bin/sh
        - -c
        - sleep infinity
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
