apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller
  namespace: kafka
  labels:
    strimzi.io/cluster: reference-kafka
spec:
  replicas: 1
  roles:
    - controller
  resources:
    requests:
      cpu: 200m
      memory: 768Mi
    limits:
      cpu: 500m
      memory: 1Gi
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        kraftMetadata: shared
        deleteClaim: false
        class: gp2
  template:
    pod:
      metadata:
        labels:
          workload-role: kafka-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: NodeGroupType
                    operator: In
                    values:
                      - workload
