apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: Namespace
metadata:
  name: spark
---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: polaris
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
