controller:
  ingressClassResource:
    name: nginx
    default: false
  ingressClass: nginx
  service:
    type: LoadBalancer
  metrics:
    enabled: true
  nodeSelector: {}
  tolerations: []
  affinity: {}
