defaultRules:
  create: false

alertmanager:
  enabled: false

grafana:
  enabled: true
  persistence:
    enabled: false
  nodeSelector:
    NodeGroupType: core
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

prometheusOperator:
  nodeSelector:
    NodeGroupType: core
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

prometheus:
  prometheusSpec:
    nodeSelector:
      NodeGroupType: core
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: gp2
          resources:
            requests:
              storage: 20Gi

kubeStateMetrics:
  nodeSelector:
    NodeGroupType: core
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi
